### PR TITLE
Create bower.json for bower support

### PR DESCRIPTION
**Pull request by sogko**
PR for issue #21
- Created initial bower.json
- Added bower_components to .gitignore

**The bower package has not been registered yet.**
After merging this PR into main repo, register it by running the following command:

```
bower register flat-ui-sass git://github.com/wingrunr21/flat-ui-sass.git
```

Thanks!

### CODE REVIEW

**Comment by wingrunr21** [comment]
Nice!

**Comment by sogko** [comment]
Hi @wingrunr21,

More info to just to complete the PR:

**Bower registration steps**
1. Tag a new release that includes bower.json: `$ git tag v.2.1.x`
2. Add `flat-ui-sass` to bower registry (hopefully no one else hijacks the name before then lol)

```
$ bower register flat-ui-sass git://github.com/wingrunr21/flat-ui-sass.git
```

**To publish a new version**, simply tag the git repo (since bower relies on git tags)

Thanks!

**Comment by wingrunr21** [comment]
Thanks, I got it above. I need to push a commit to set the version then I'll push it to bower.

**Comment by wingrunr21** [comment]
Note that as v2.1.3 was already tagged and cut, that won't be retagged. I'm planning on doing the work to upgrade to new versions of Flat UI and those will be when bower is officially supported.

**Pull request merged**
